from types import Twist
from math import pi

M_TO_PIXELS = 200

MAX_LINEAR_SPEED = 0.5 * M_TO_PIXELS
MAX_ANGULAR_SPEED = 1.0 * 2 * pi

# The types of objects as powers of two, used for filtering shapes
WALL_MASK = 1
ROBOT_MASK = 2
ARC_LANDMARK_MASK = 4
POLE_LANDMARK_MASK = 8
BLAST_LANDMARK_MASK = 16
ANY_LANDMARK_MASK = ARC_LANDMARK_MASK | POLE_LANDMARK_MASK | BLAST_LANDMARK_MASK
RED_PUCK_MASK = 32
GREEN_PUCK_MASK = 64
BLUE_PUCK_MASK = 128
ANY_PUCK_MASK = RED_PUCK_MASK | GREEN_PUCK_MASK | BLUE_PUCK_MASK
